CREATE TABLE IF NOT EXISTS `facilities` (
  `id` int NOT NULL AUTO_INCREMENT,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ownerfk` int DEFAULT NULL,
  `submitted_by` varchar(80) NOT NULL,
  `submitter_type` varchar(20) NOT NULL,
  `name` varchar(160) NOT NULL,
  `address` varchar(180) NOT NULL,
  `city` varchar(50) DEFAULT NULL,
  `province_state` varchar(20) NOT NULL,
  `country` varchar(20) NOT NULL,
  `postal` varchar(10) NOT NULL,
  `email` varchar(160) NOT NULL,
  `phone` varchar(16) NOT NULL,
  `website` varchar(512) NOT NULL,
  `approval_status` enum('pending','approved','rejected') DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `upvotes` int DEFAULT '0',
  `downvotes` int DEFAULT '0',
  `diesel` tinyint(1) DEFAULT '0',
  `washroom` tinyint(1) DEFAULT '0',
  `shower` tinyint(1) DEFAULT '0',
  `reststop` tinyint(1) DEFAULT '0',
  `coffee` tinyint(1) DEFAULT '0',
  `snacks` tinyint(1) DEFAULT '0',
  `meal` tinyint(1) DEFAULT '0',
  `drivethrough` tinyint(1) DEFAULT '0',
  `walkthrough` tinyint(1) DEFAULT '0',
  `otherservices` varchar(512) DEFAULT NULL,
  `lat` float(10,6) NOT NULL,
  `lng` float(10,6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `lat` (`lat`,`lng`,`upvotes`,`downvotes`,`diesel`,`washroom`,`shower`,`reststop`,`coffee`,`snacks`,`meal`,`drivethrough`,`walkthrough`),
  KEY `approval_status` (`approval_status`),
  FULLTEXT KEY `otherservices` (`otherservices`)
) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;